export const WORKFLOW_REPOSITORY = Symbol('WORKFLOW_REPOSITORY');
export const WORKFLOW_TRIGGER_REPOSITORY = Symbol('WORKFLOW_TRIGGER_REPOSITORY');
export const WORKFLOW_STEP_REPOSITORY = Symbol('WORKFLOW_STEP_REPOSITORY');
export const WORKFLOW_EXIT_CONDITION_REPOSITORY = Symbol('WORKFLOW_EXIT_CONDITION_REPOSITORY');
export const WORKFLOW_STEP_CONDITION_REPOSITORY = Symbol('WORKFLOW_STEP_CONDITION_REPOSITORY');
